FROM python:3.12.2-alpine3.19

ARG PLEX_URL
ARG PLEX_TOKEN
ARG STREAMABLE_LOGIN
ARG STREAMABLE_PASSWORD
ARG TZ

RUN apk --no-cache add ffmpeg

ENV PLEX_URL=$PLEX_URL
ENV PLEX_TOKEN=$PLEX_TOKEN
ENV STREAMABLE_LOGIN=$STREAMABLE_LOGIN
ENV STREAMABLE_PASSWORD=$STREAMABLE_PASSWORD
ENV TZ=$TZ

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt
RUN set FLASK_APP=main.py

CMD flask --app main run --host 0.0.0.0
